# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  replicaCount: 1
  image:
    name: 
    tag: latest

# DB Settings
replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: 14.1.0

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  size: 8Gi

postgresql:
  username: postgres
  password: root
  database: forum
  host: db